apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: uq6tx21lc-java-springboot 
  janus-idp.io/tekton: uq6tx21lc-java-springboot
  backstage.io/kubernetes-id: uq6tx21lc-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: uq6tx21lc-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml