apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: uq6tx21lc-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:2eef375f70c4b879a25d80005bae96cb647a272c@sha256:d2f3adac418f1e9dc9ab60842f5423b6223bcbe7edbabcfe54edb87b8d965a5b
          name: container-image
