apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: uq6tx21lc-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/uq6tx21lc-java-springboot-gitops